FROM golang:latest

EXPOSE 3000 4000 8080
ENV PORT=8080

ARG WORKDIR
WORKDIR $WORKDIR

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN CGO_ENABLED=0i go build -gcflags "all=-N -l" -o main .

CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "/app/main" ]