package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"cashflow/api/graph/generated"
	"cashflow/models"
	"cashflow/utils"
	"context"
	"fmt"
	"time"
)

// CreateBalance is the resolver for the createBalance field.
func (r *mutationResolver) CreateBalance(ctx context.Context, input generated.NewBalance) (*models.Balance, error) {
	newBalance, err := (*r.BalanceService).WriteBalance(input.Amount, input.Date)
	return &newBalance, err
}

// DeleteBalance is the resolver for the deleteBalance field.
func (r *mutationResolver) DeleteBalance(ctx context.Context, date string) (string, error) {
	return date, (*r.BalanceService).DeleteBalance(ctx, date)
}

// ListBalances is the resolver for the listBalances field.
func (r *queryResolver) ListBalances(ctx context.Context, from *time.Time, to *time.Time) ([]*models.Balance, error) {
	if from == nil || to == nil {
		err := fmt.Errorf("please provide from and to dates")
		return nil, err
	}

	balances, err := (*r.BalanceService).ListBalances(*from, *to)
	return utils.ConvertStructToPointersArray(balances), err
}
